fn main() -> Result<(), std::io::Error> {
    server::main()
}